sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t goxx/react-docker-dev . 
scripts:
  - docker run -e CI=true goxx/react-docker-dev npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-841732415283"
  bucket_path: "react-app"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  on: 
    branch: main
